### ISSUE TITLE
Implement the php-reflection library

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#207]
Replace the php-parser library with the newly created [php-reflection](https://github.com/glayzzle/php-reflection) library.

It may be easier to rewrite the plugin from scratch than to try to pick everything apart ???

**Comment by ichiriac** [comment]
Todo list on server side : 

- [ ]  find a way to be able to debug and use breakpoints (if it's not easy / possible from vscode, use something like https://github.com/node-inspector/node-inspector)
- [ ] bootstrap a test in order to provide autocomplete
- [ ] implement the caching layer
- [ ] handle the stubs but with a generic JSON/cache ready way

Todolist from the client :

- [ ] Handle communication with server for autocomplete
- [ ] Implement a Validation Provider
- [ ] Implement a SignatureHelpProvider
- [ ] Implement a Hover Provider
- [ ] Implement a CodeLens Provider
- [ ] Get ideas from https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts

**Comment by ichiriac** [comment]
Found from vscode code https://code.visualstudio.com/Docs/editor/debugging#_multitarget-debugging the way to start debug with breakpoints on server & client from a single editor instance.

Now for running the extension, must start the `Launch Client/Server` target.

**Comment by ichiriac** [comment]
In order make everything run :

```
cd client
ln -s ../server src-server
cd src-server
npm run watch
```

> On windows use this : http://superuser.com/questions/1020821/how-to-create-a-symbolic-link-on-windows-10

By opening the `client` folder from vscode a new folder `src-server` was created. You can edit sources and run the `Launch Client/Server` according.

To add a break point, I was unable to do it from TS files, must go on server/...js file and add a breakpoint, it will work but without the TS source - maybe a workaround exists
