### ISSUE TITLE
Code Inspections

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#260]
General
- [ ] Unreachable code (after `return`, etc)
- [ ] Assignment instead of comparison in `if` statements
- [ ] High cyclomatic complexity

Undefined
- [ ] Undefined class/trait/interface
- [ ] Undefined variable/const
- [ ] Undefined function
- [ ] Undefined class property/method/const

Unused
- [ ] Unused variable/parameter/const
- [ ] Unused function
- [ ] Unused class property/method

Classes
- [ ] Unimplemented interface
- [ ] Unimplemented abstract method

_more to follow_

**Comment by TheColorRed** [comment]
These linting features should have a config associated with them like JSLint.

JSLint allows you to specify the following for each item:

* Error
* Warning
* Off

**Comment by ichiriac** [comment]
First prototype, replace `php -l` by checking syntax : 

![image](https://cloud.githubusercontent.com/assets/173203/24074461/86b2ef56-0c09-11e7-87bd-8bbec4bdec09.png)

Working on code here : https://github.com/glayzzle/crane/tree/feature/validator

**Comment by ichiriac** [comment]
We should fix or look at another definition on stubs because they contain parse errors :

```sh
php -l /home/devbox/Crane/phpstubs/crane-php-stubs-master/Core.php
PHP Fatal error:  Access type for interface method IteratorAggregate::getIterator() must be omitted in /home/devbox/Crane/phpstubs/crane-php-stubs-master/Core.php on line 28

Fatal error: Access type for interface method IteratorAggregate::getIterator() must be omitted in /home/devbox/Crane/phpstubs/crane-php-stubs-master/Core.php on line 28
```

An `interface` method declaration can't be `abstract` as they are already into an interface, and also can't impose at classes to declare abstract methods (does not makes sens anyway)
