### ISSUE TITLE
Performance Optimisation

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#37]
For large projects, the performance of Crane can be pretty shocking.

We need to review the extension and improve the performance as much as possible.

- [x] ~~Handle file errors~~
- [x] ~~Resolve issue with loading too many files at once~~
- [x] ~~Parsing large projects efficiently~~
- [x] Profile for memory leaks **`delay until 0.2`**
- [x] Other improvements **`delay until 0.2`**

---

http://stackoverflow.com/a/30087518/492298
https://hacks.mozilla.org/2012/11/tracking-down-memory-leaks-in-node-js-a-node-js-holiday-season/
https://strongloop.com/node-js/node-js-performance-tips/

**Comment by TheColorRed** [comment]
I think I have a solution for this, I have it processing many files without locking up (at least I haven't had it lock up yet)...

**Comment by TheColorRed** [comment]
According to the vscode documentation:

> The workspace offers support for listening to fs events and for finding files. Both perform well and run outside the editor-process so that they should be always used instead of nodejs-equivalents.

So What I have done is removed `glob` from the server and replaced it with `workspace.findFiles` which is in the client (since it has access to `workspace`). We send the array of file paths to the server, which then process each file in the same way that glob did.

The issue I am having (which can be found in both the `glob` implementation and this one), is that it is getting stuck processing some files (but doesn't crash the editor). I am not sure what the cause is, because it processes the same file some times but not others (no error is thrown). Might be a memory issue...

**Comment by nevadascout** [comment]
How about setting a timeout for the processing of each file?

If it times out then try it again, up to a max of 3 times, maybe?

**Comment by TheColorRed** [comment]
Processing 1,000 files takes about 5 seconds
```
Files to parse: 2569
/* Output snipped */
Parsed file: c:\Users\rnaddy\Documents\www\rewards-service\vendor\fzaninotto\faker\src\Faker\Provider\cs_CZ\Text.php
(1046)Processed file: c:\Users\rnaddy\Documents\www\rewards-service\vendor\fzaninotto\faker\src\Faker\Provider\cs_CZ\Text.php
```

I am getting many of these errors which could be why it never completes, as it probably isn't processing it.

```
errno:-4066
code:"EMFILE"
syscall:"open"
path:"c:\Path\to\File.php"
```

**Comment by TheColorRed** [comment]
By using a filequeue: https://www.npmjs.com/package/filequeue

I am able to read about 400 more documents.

**Comment by TheColorRed** [comment]
I think I have come to the conclusion, that all files are sharing the same instance of the treeBuilder or the php-parser making it so newer files results return throwing the old results away.

Here are the files it wants to process:
```
0:"c:\Users\rnaddy\Documents\www\piephp\framework\autoload.php"
1:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Pie.php"
2:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\App.php"
3:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Call.php"
4:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Controller.php"
5:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Env.php"
6:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Event.php"
7:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\RootScope.php"
8:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Scope.php"
9:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Service.php"
10:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Module.php"
11:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Taste\Browser.php"
12:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Taste\Test.php"
13:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\App.php"
14:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\ApplicationController.php"
15:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Controller.php"
16:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Object.php"
17:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Response.php"
18:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Pie.php"
19:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\View.php"
20:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Collections\ArrayList.php"
21:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Collections\Collection.php"
22:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Collections\Linq.php"
23:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Net\Request.php"
24:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Net\Response.php"
25:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Util\ArrayList.php"
26:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Util\Math.php"
27:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Util\Validation.php"
28:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Cache\Cache.php"
29:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Cache\module.php"
30:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Database\Db.php"
31:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Database\Model.php"
32:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Database\ResultSet.php"
33:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Database\Sub.php"
34:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Database\module.php"
35:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Http\Http.php"
36:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Http\HttpRequest.php"
37:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Http\HttpResult.php"
38:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Http\module.php"
39:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\Media.php"
41:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Route\Route.php"
42:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Route\RouteParams.php"
43:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Route\module.php"
44:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Session\Session.php"
45:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Session\module.php"
46:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\Element.php"
47:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\RepeatInfo.php"
40:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\module.php"
48:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\Tpl.php"
49:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\TplAttr.php"
50:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\module.php"
51:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Console\Command.php"
52:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Console\Console.php"
53:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Database\Db.php"
54:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Database\Model.php"
55:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Database\ResultSet.php"
56:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Database\Row.php"
57:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Helper\functions.php"
58:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Routes\Path.php"
59:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Routes\RequestType.php"
60:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Routes\Route.php"
61:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Server\Server.php"
62:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Collections\Processors\ArrayListProcessor.php"
63:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Collections\Processors\IParser.php"
64:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Collections\Processors\MysqlProcessor.php"
65:"c:\Users\rnaddy\Documents\www\piephp\framework\src\Collections\Processors\Processor.php"
66:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Cache\Caches\File.php"
67:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Cache\Interfaces\ICache.php"
68:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\Sources\Audio.php"
69:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\Sources\Image.php"
70:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\Sources\Video.php"
71:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\filters\date.php"
72:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\filters\number.php"
73:"c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\filters\string.php"
```

Here is what actually gets processed:
```
0 (1 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Controller.php
1 (2 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Call.php
2 (3 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\RootScope.php
3 (4 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\autoload.php
4 (5 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Event.php
5 (6 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Env.php
6 (7 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Controller.php
7 (8 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Response.php
8 (9 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\View.php
9 (10 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Crust\Util\Math.php
10 (11 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Cache\module.php
11 (12 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Database\Sub.php
12 (13 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Database\module.php
13 (14 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Http\HttpRequest.php
14 (15 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Http\HttpResult.php
15 (16 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Http\module.php
16 (17 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\module.php
17 (18 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Route\RouteParams.php
18 (19 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Session\module.php
19 (20 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Route\module.php
20 (21 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\RepeatInfo.php
21 (22 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\module.php
22 (23 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Database\Row.php
23 (24 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Helper\functions.php
24 (25 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Routes\RequestType.php
25 (26 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\src\Application\Server\Server.php
26 (27 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\src\Collections\Processors\IParser.php
27 (28 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\Sources\Audio.php
28 (29 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Cache\Interfaces\ICache.php
29 (30 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\Sources\Image.php
30 (31 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Media\Sources\Video.php
31 (32 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\filters\date.php
32 (33 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\filters\number.php
33 (34 of 74) File: c:\Users\rnaddy\Documents\www\piephp\framework\Pie1.php\Modules\Tpl\filters\string.php
```

**Comment by TheColorRed** [comment]
Finally I Figured it out!

Somewhere in the treeBuilder This is getting thrown:

    [TypeError: Cannot read property '0' of null]

**Comment by nevadascout** [comment]
Sounds like it's trying to access an array index of a non-array

**Comment by TheColorRed** [comment]
Yeah. When files load it handles the errors. I am now able to handle and read all files in the workspace with ease! The fix is in the pull request #45

**Comment by TheColorRed** [comment]
To improve performance we now use workbench's built in function `workbench.findFIles()` instead of `glob()` as it runs outside of the editor (basically in it's own thread) so it doesn't lock up the editor.

A new helpful feature:

- The status bar now also shows the number of files process, the total to be processed and the percent complete. (`(123 of 3454 / 1.05%)`)

Workbench size (No longer locks up editor):

![capture](https://cloud.githubusercontent.com/assets/1571806/15231042/7e2bc456-185e-11e6-8042-0b9342433004.PNG)

Approximate scan time: 20s

**Comment by nevadascout** [comment]
Great work! Looking forward to seeing this pull request

When you make it, please select `develop` as the target branch!

**Comment by TheColorRed** [comment]
You have already pulled this into the master branch.

My next thoughts for optimization would be to cache the file in a project folder, so when the project loads the second, third, fourth, etc. time it just loads the file. Testing the above folder, initial load time is 20s, loading it from the cached file takes < 5s and doesn't have to scan the files again.

Two additional settings would be added:

```
"crane.isProject": {
    "type": "boolean",
    "default": true,
    "description": "Turning the project on will allow crane to load faster when reloading the project"
},
"crane.projectFolder": {
    "type": "string",
    "default": ".crane",
    "description": "Sets the default project folder for Crane"
}
```

An additional Command would be added:

```
{
    "command": "crane.rebuildSources",
    "title": "Crane - Rebuild Sources"
}
```

This command will rebuild the projects sources and save them to the project file assuming they have projects enabled.

Once the projects folder gets created a `.gitignore` file will be added to that directory so files in the directory do not get put into the user's git repo; they could however edit or remove the `.gitignore` file if they would like.

When saving the tree, it will get `gzipped` and saved into `.crane/tree`.

With my tests a non-gzip tree file size is **9,500k**
And a gzipped version of the tree is **770k**

This project's folder (`.crane`) could also contain all of the 3rd-party files (#35 & #36) if the user wishes to download them. They the would also be compiled into the `tree` file.

**Comment by nevadascout** [comment]
Sounds good to me, however I think putting the cache in the project folder would be a mistake.

Instead, lets put it in `%appdata%` on windows and in a hidden folder in the home directory on linux/OSX.

My suggestion is to generate a simple hash of the workspace directory and use that as the folder name. For example:

Workspace folder: `C:/users/ns/projects/myproject/`
Hash: `uef5vbrtfeo8`

Cache folder system:

```
%APPDATA%
    \ crane
       \ uef5vbrtfeo8
         \ tree.cache
       \ nyf9psbtd9rg
         \ tree.cache

```
Each workspace gets a separate folder inside the crane directory to store the cache files in.

This prevents needing to update the gitignore and keeps the workspace folder clean. This is especially important because some git tools update diffs whenever any file in a workspace changes, and if we're constantly modifying cache files then this could cause an issue.
